export const metadata = {
  title: "My-Classroom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body className="vsc-initialized" style={{ backgroundColor: 'gray' }}>
        <div className="h-screen w-full"> {children} </div>
      </body>
    </html>

  );
}
